/**
 * This source file is part of the Apiboost(R) OmniSpec Core.
 *
 * Copyright (c) Apiboost, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * See LICENSE.md and LICENSING.md in the project root for license information.
 */

import type { ThemeTokens } from '../types/theme.types'

export const lightTheme: ThemeTokens = {
  '--omnispec-bg-primary': '#ffffff',
  '--omnispec-bg-secondary': '#f8f9fa',
  '--omnispec-bg-tertiary': '#f1f3f5',
  '--omnispec-bg-code': '#f5f5f5',

  '--omnispec-fg-primary': '#1a1a2e',
  '--omnispec-fg-secondary': '#4a4a6a',
  '--omnispec-fg-muted': '#8c8ca1',
  '--omnispec-fg-code': '#d63384',
  '--omnispec-fg-link': '#0969da',

  '--omnispec-color-primary': '#0969da',
  '--omnispec-color-primary-hover': '#0550ae',
  '--omnispec-color-primary-text': '#ffffff',

  '--omnispec-color-get': '#1a7f37',
  '--omnispec-color-post': '#0550ae',
  '--omnispec-color-put': '#bf8700',
  '--omnispec-color-delete': '#cf222e',
  '--omnispec-color-patch': '#8250df',

  '--omnispec-color-publish': '#0550ae',
  '--omnispec-color-subscribe': '#1a7f37',

  '--omnispec-color-success': '#1a7f37',
  '--omnispec-color-warning': '#bf8700',
  '--omnispec-color-error': '#cf222e',
  '--omnispec-color-info': '#0550ae',

  '--omnispec-border-color': '#d0d7de',
  '--omnispec-border-radius': '0.375rem',
  '--omnispec-input-bg': '#ffffff',
  '--omnispec-input-border': '#d0d7de',

  '--omnispec-nav-bg': '#f6f8fa',
  '--omnispec-nav-text': '#1a1a2e',
  '--omnispec-nav-hover-bg': '#eaeef2',
  '--omnispec-nav-accent': '#0969da',
  '--omnispec-nav-active-bg': '#eaeef2',
  '--omnispec-nav-active-border-width': '0.1875rem',
  '--omnispec-nav-item-padding-v': '0.625rem',
  '--omnispec-nav-item-padding-h': '0.75rem',
  '--omnispec-nav-indent': '0.875rem',
  '--omnispec-nav-item-gap': '0.5rem',
  '--omnispec-nav-item-radius': '0',
  '--omnispec-nav-group-font-size': '0.8125rem',
  '--omnispec-nav-group-font-weight': '600',
  '--omnispec-nav-group-letter-spacing': '0.04em',
  '--omnispec-nav-group-text-transform': 'uppercase',
  '--omnispec-nav-badge-radius': '0.25rem',
  '--omnispec-nav-badge-text': '#ffffff',
  '--omnispec-nav-width': '18.75rem',
  '--omnispec-nav-divider-color': '#d0d7de',
  '--omnispec-nav-heading-color': '#8c8ca1',

  '--omnispec-scrollbar-width': '0.5rem',
  '--omnispec-scrollbar-track': 'transparent',
  '--omnispec-scrollbar-thumb': '#c1c7cd',
  '--omnispec-scrollbar-thumb-hover': '#a0a8b0',

  '--omnispec-font-sans': '-apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif',
  '--omnispec-font-mono': 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
  '--omnispec-font-size-base': '0.9375rem',
  '--omnispec-font-size-md': '1rem',
  '--omnispec-font-size-sm': '0.8125rem',
  '--omnispec-font-size-xs': '0.75rem',
  '--omnispec-font-size-xxs': '0.625rem',
  '--omnispec-font-size-lg': '1rem',
  '--omnispec-font-size-xl': '1.25rem',

  '--omnispec-h1-font-size': '1.75rem',
  '--omnispec-h1-font-weight': '800',
  '--omnispec-h1-color': '#1a1a2e',
  '--omnispec-h2-font-size': '1.25rem',
  '--omnispec-h2-font-weight': '700',
  '--omnispec-h2-color': '#1a1a2e',
  '--omnispec-h3-font-size': '1rem',
  '--omnispec-h3-font-weight': '600',
  '--omnispec-h3-color': '#1a1a2e',

  '--omnispec-btn-font-size': '0.8125rem',
  '--omnispec-btn-radius': '0.375rem',
  '--omnispec-btn-primary-bg': '#0969da',
  '--omnispec-btn-primary-text': '#ffffff',
  '--omnispec-btn-primary-bg-hover': '#0550ae',
  '--omnispec-btn-primary-text-hover': '#ffffff',
  '--omnispec-btn-primary-shadow': 'none',
  '--omnispec-btn-primary-shadow-hover': 'none',
  '--omnispec-btn-secondary-bg': '#f8f9fa',
  '--omnispec-btn-secondary-text': '#1a1a2e',
  '--omnispec-btn-secondary-bg-hover': '#eaeef2',
  '--omnispec-btn-secondary-text-hover': '#1a1a2e',
  '--omnispec-btn-secondary-shadow': 'none',
  '--omnispec-btn-secondary-shadow-hover': 'none',
}

export const darkTheme: ThemeTokens = {
  '--omnispec-bg-primary': '#0d1117',
  '--omnispec-bg-secondary': '#161b22',
  '--omnispec-bg-tertiary': '#21262d',
  '--omnispec-bg-code': '#1c2128',

  '--omnispec-fg-primary': '#e6edf3',
  '--omnispec-fg-secondary': '#b1bac4',
  '--omnispec-fg-muted': '#7d8590',
  '--omnispec-fg-code': '#ff7b72',
  '--omnispec-fg-link': '#58a6ff',

  '--omnispec-color-primary': '#58a6ff',
  '--omnispec-color-primary-hover': '#79c0ff',
  '--omnispec-color-primary-text': '#0d1117',

  '--omnispec-color-get': '#3fb950',
  '--omnispec-color-post': '#58a6ff',
  '--omnispec-color-put': '#d29922',
  '--omnispec-color-delete': '#f85149',
  '--omnispec-color-patch': '#bc8cff',

  '--omnispec-color-publish': '#58a6ff',
  '--omnispec-color-subscribe': '#3fb950',

  '--omnispec-color-success': '#3fb950',
  '--omnispec-color-warning': '#d29922',
  '--omnispec-color-error': '#f85149',
  '--omnispec-color-info': '#58a6ff',

  '--omnispec-border-color': '#30363d',
  '--omnispec-border-radius': '0.375rem',
  '--omnispec-input-bg': '#0d1117',
  '--omnispec-input-border': '#30363d',

  '--omnispec-nav-bg': '#161b22',
  '--omnispec-nav-text': '#e6edf3',
  '--omnispec-nav-hover-bg': '#21262d',
  '--omnispec-nav-accent': '#58a6ff',
  '--omnispec-nav-active-bg': '#21262d',
  '--omnispec-nav-active-border-width': '0.1875rem',
  '--omnispec-nav-item-padding-v': '0.625rem',
  '--omnispec-nav-item-padding-h': '0.75rem',
  '--omnispec-nav-indent': '0.875rem',
  '--omnispec-nav-item-gap': '0.5rem',
  '--omnispec-nav-item-radius': '0',
  '--omnispec-nav-group-font-size': '0.8125rem',
  '--omnispec-nav-group-font-weight': '600',
  '--omnispec-nav-group-letter-spacing': '0.04em',
  '--omnispec-nav-group-text-transform': 'uppercase',
  '--omnispec-nav-badge-radius': '0.25rem',
  '--omnispec-nav-badge-text': '#ffffff',
  '--omnispec-nav-width': '18.75rem',
  '--omnispec-nav-divider-color': '#30363d',
  '--omnispec-nav-heading-color': '#7d8590',

  '--omnispec-scrollbar-width': '0.5rem',
  '--omnispec-scrollbar-track': 'transparent',
  '--omnispec-scrollbar-thumb': '#484f58',
  '--omnispec-scrollbar-thumb-hover': '#6e7681',

  '--omnispec-font-sans': '-apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif',
  '--omnispec-font-mono': 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
  '--omnispec-font-size-base': '0.9375rem',
  '--omnispec-font-size-md': '1rem',
  '--omnispec-font-size-sm': '0.8125rem',
  '--omnispec-font-size-xs': '0.75rem',
  '--omnispec-font-size-xxs': '0.625rem',
  '--omnispec-font-size-lg': '1rem',
  '--omnispec-font-size-xl': '1.25rem',

  '--omnispec-h1-font-size': '1.75rem',
  '--omnispec-h1-font-weight': '800',
  '--omnispec-h1-color': '#e6edf3',
  '--omnispec-h2-font-size': '1.25rem',
  '--omnispec-h2-font-weight': '700',
  '--omnispec-h2-color': '#e6edf3',
  '--omnispec-h3-font-size': '1rem',
  '--omnispec-h3-font-weight': '600',
  '--omnispec-h3-color': '#e6edf3',

  '--omnispec-btn-font-size': '0.8125rem',
  '--omnispec-btn-radius': '0.375rem',
  '--omnispec-btn-primary-bg': '#58a6ff',
  '--omnispec-btn-primary-text': '#0d1117',
  '--omnispec-btn-primary-bg-hover': '#79c0ff',
  '--omnispec-btn-primary-text-hover': '#0d1117',
  '--omnispec-btn-primary-shadow': 'none',
  '--omnispec-btn-primary-shadow-hover': 'none',
  '--omnispec-btn-secondary-bg': '#21262d',
  '--omnispec-btn-secondary-text': '#e6edf3',
  '--omnispec-btn-secondary-bg-hover': '#30363d',
  '--omnispec-btn-secondary-text-hover': '#e6edf3',
  '--omnispec-btn-secondary-shadow': 'none',
  '--omnispec-btn-secondary-shadow-hover': 'none',
}
